"""Posterior predictive checks and harmonized Model 2 vs Model 3 comparison.

This script expects final production InferenceData NetCDF files generated by
05_wash_model.py and 06_maternal_education_model.py. It intentionally performs
model comparison only on the same 4,503-child complete-maternal-information
sample.
"""
from pathlib import Path
import numpy as np
import pandas as pd
import arviz as az
import matplotlib.pyplot as plt

OUT = Path("results/model_outputs")
TABLES = Path("results/tables")
FIGURES = Path("results/figures")
TABLES.mkdir(parents=True, exist_ok=True)
FIGURES.mkdir(parents=True, exist_ok=True)

def main():
    m2 = az.from_netcdf(OUT / "model2_wash_harmonized.nc")
    m3 = az.from_netcdf(OUT / "model3_maternal_education.nc")

    # Recompute pointwise log likelihood if absent.
    if "log_likelihood" not in m2.groups() or "log_likelihood" not in m3.groups():
        raise RuntimeError(
            "Final NetCDF files must include pointwise log_likelihood. "
            "Regenerate them with a compatible PyMC/ArviZ environment."
        )

    w2 = az.waic(m2, pointwise=True)
    w3 = az.waic(m3, pointwise=True)
    comp = az.compare({"Model 2 harmonized": m2, "Model 3": m3}, ic="waic")
    comp.to_csv(TABLES / "model_predictive_comparison_production.csv")

    if "posterior_predictive" in m3.groups():
        yrep = np.asarray(m3.posterior_predictive["stunted"])
        observed = np.asarray(m3.observed_data["stunted"])
        pd.DataFrame({
            "observed_prevalence": [observed.mean()],
            "replicated_mean": [yrep.mean(axis=(-1, 0, 1)) if yrep.ndim > 1 else yrep.mean()],
        }).to_csv(TABLES / "model3_ppc_overall_production.csv", index=False)

    print("Model 2 WAIC:", float(-2 * w2.elpd_waic))
    print("Model 3 WAIC:", float(-2 * w3.elpd_waic))
    print(comp)

if __name__ == "__main__":
    main()
